source $HOME/.config/nvim/vim/plug.vim
source $HOME/.config/nvim/vim/set.vim
source $HOME/.config/nvim/vim/style.vim
source $HOME/.config/nvim/vim/map.vim
source $HOME/.config/nvim/vim/func.vim
source $HOME/.config/nvim/lua/style.lua
source $HOME/.config/nvim/lua/tele.lua
source $HOME/.config/nvim/lua/lline.lua
source $HOME/.config/nvim/coc/coc.vim
